project_name: axiom

before:
  hooks:
    - make man

builds:
  - <<: &build_defaults
      binary: axiom
      main: ./cmd/axiom
      env:
        - CGO_ENABLED=0
      tags:
        - osusergo
        - netgo
        - static_build
      flags:
        - -buildvcs=false
        - -buildmode=pie
        - -installsuffix=cgo
        - -trimpath
      ldflags:
        - -s -w -extldflags "-fno-PIC -static -Wl -z now -z relro"
        - -X github.com/axiomhq/pkg/version.release={{ .Version }}
        - -X github.com/axiomhq/pkg/version.revision={{ .ShortCommit }}
        - -X github.com/axiomhq/pkg/version.buildDate={{ .CommitDate }}
        - -X github.com/axiomhq/pkg/version.buildUser=goreleaser
      mod_timestamp: "{{ .CommitTimestamp }}"
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - <<: *build_defaults
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    
  - <<: *build_defaults
    flags:
      - -buildvcs=false
      - -buildmode=exe
      - -installsuffix=cgo
      - -trimpath
    id: linux-no-pie
    goos:
      - linux
    goarch:
      - arm
      - 386
    goarm:
      - 6
      - 7

  - <<: *build_defaults
    flags:
      - -buildvcs=false
      - -buildmode=exe
      - -installsuffix=cgo
      - -trimpath
    id: docker
    goos:
      - linux
    goarch:
      - amd64

  - <<: *build_defaults
    id: windows
    goos:
      - windows
    goarch:
      - amd64
      - 386

archives:
  - <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    id: nix
    builds:
      - darwin
      - linux
      - linux-no-pie
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - man/{{ .ProjectName }}*.1
  - <<: *archive_defaults
    id: windows
    builds:
      - windows
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

milestones:
  - repo:
      owner: axiomhq
      name: cli
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: cli
  prerelease: auto
  name_template: Axiom CLI v{{ .Version }}

brews:
  - name: axiom
    description: Powerful log analytics from the comfort of your command-line
    homepage: https://axiom.co
    license: MIT
    tap:
      owner: axiomhq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: axiom-automation
      email: hello@axiom.co
    skip_upload: auto
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      man1.install Dir["man/{{ .ProjectName }}*.1"]
      (bash_completion/"{{ .ProjectName }}").write `#{bin}/{{ .ProjectName }} completion bash`
      (fish_completion/"{{ .ProjectName }}.fish").write `#{bin}/{{ .ProjectName }} completion fish`
      (zsh_completion/"_{{ .ProjectName }}").write `#{bin}/{{ .ProjectName }} completion zsh`
    test: |
      assert_match "Axiom CLI version #{version}", shell_output("#{bin}/{{ .ProjectName }} -v")

dockers:
  - ids:
      - docker
    image_templates:
      - "docker.io/axiomhq/cli:{{ .Major }}"
      - "docker.io/axiomhq/cli:{{ .Major }}.{{ .Minor }}"
      - "docker.io/axiomhq/cli:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "docker.io/axiomhq/cli:latest"
      - "ghcr.io/axiomhq/cli:{{ .Major }}"
      - "ghcr.io/axiomhq/cli:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/axiomhq/cli:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/axiomhq/cli:latest"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://axiom.co
      - --label=org.opencontainers.image.source=https://github.com/axiomhq/cli
      - --label=org.opencontainers.image.documentation=https://docs.axiom.co/reference/CLI
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.author=Axiom, Inc. <info@axiom.co>
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.vendor=Axiom, Inc.

aurs:
  - name: axiom-bin
    ids:
      - axiom
    homepage: "https://www.axiom.co/"
    description: "Powerful log analytics from the comfort of your command-line"
    maintainers:
      - 'tyler <tyler@axiom.co>'
      - 'axiom <hello@axiom.co>'
    license: "MIT"
    private_key : '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/axiom-bin.git'
    provides:
      - axiom
    package: |-
      # binary file
      install -Dm755 "./axiom" "${pkgdir}/usr/bin/axiom"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/axiom/LICENSE"
    commit_author:
      name: axiom
      email: hello@axiom.co
